version: '3.8'

services:
  vh-db:
    build:
      context: ./vh-bots-db/
    image: vh-bots/db
    ports:
      - 8529:8529
    volumes:
      - vh-db:/var/lib/arangodb3
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
    container_name: 'vh-db'

  vh-giveaway-bot:
    build:
      context: ./vh-bots-giveaways/
      args:
        - BOT_TOKEN=
        - CONFIG_FILE=config_test.json
    depends_on:
      - "vh-db"
    image: vh-bots/giveaways
    container_name: 'vh-giveaway-bot'

volumes:
  vh-db:
