version: '3.8'

services:
  vh-db:
    build:
      context: ./vh-bots-db/
    image: vh-bots/db
    ports:
      - 8529:8529
    volumes:
      - vh-db:/var/lib/arangodb3
    environment:
      - ARANGO_RANDOM_ROOT_PASSWORD=1
    container_name: 'vh-db'

  vh-giveaway-bot:
    build:
      context: ./vh-bots-giveaways/
      args:
        - GIVEAWAY_BOT_TOKEN=
        - GIVEAWAY_CONFIG_FILE=config_test.json
    depends_on:
      - "vh-db"
    image: vh-bots/giveaways
    container_name: 'vh-giveaway-bot'

  vh-queue-bot:
    build:
      context: ./vh-bots-queues/
      args:
        - QUEUE_BOT_TOKEN=
        - QUEUE_CONFIG_FILE=config.json
    depends_on:
      - "vh-db"
    image: vh-bots/queues
    container_name: 'vh-queue-bot'

volumes:
  vh-db:
